# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import kv_pb2 as kv__pb2


class KVServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Put = channel.unary_unary(
                '/kv.KVServer/Put',
                request_serializer=kv__pb2.KVRequest.SerializeToString,
                response_deserializer=kv__pb2.KVResponse.FromString,
                )
        self.GetLocal = channel.unary_unary(
                '/kv.KVServer/GetLocal',
                request_serializer=kv__pb2.KVRequest.SerializeToString,
                response_deserializer=kv__pb2.KVResponse.FromString,
                )
        self.GetGlobal = channel.unary_unary(
                '/kv.KVServer/GetGlobal',
                request_serializer=kv__pb2.KVRequest.SerializeToString,
                response_deserializer=kv__pb2.KVResponse.FromString,
                )
        self.Delete = channel.unary_unary(
                '/kv.KVServer/Delete',
                request_serializer=kv__pb2.KVRequest.SerializeToString,
                response_deserializer=kv__pb2.KVResponse.FromString,
                )


class KVServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Put(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLocal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGlobal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KVServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Put': grpc.unary_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=kv__pb2.KVRequest.FromString,
                    response_serializer=kv__pb2.KVResponse.SerializeToString,
            ),
            'GetLocal': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLocal,
                    request_deserializer=kv__pb2.KVRequest.FromString,
                    response_serializer=kv__pb2.KVResponse.SerializeToString,
            ),
            'GetGlobal': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGlobal,
                    request_deserializer=kv__pb2.KVRequest.FromString,
                    response_serializer=kv__pb2.KVResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=kv__pb2.KVRequest.FromString,
                    response_serializer=kv__pb2.KVResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kv.KVServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class KVServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kv.KVServer/Put',
            kv__pb2.KVRequest.SerializeToString,
            kv__pb2.KVResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLocal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kv.KVServer/GetLocal',
            kv__pb2.KVRequest.SerializeToString,
            kv__pb2.KVResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetGlobal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kv.KVServer/GetGlobal',
            kv__pb2.KVRequest.SerializeToString,
            kv__pb2.KVResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kv.KVServer/Delete',
            kv__pb2.KVRequest.SerializeToString,
            kv__pb2.KVResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
