# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kv.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08kv.proto\x12\x02kv\"J\n\tKVRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\x12\x0f\n\x07version\x18\x03 \x01(\x04\x12\x10\n\x08operator\x18\x04 \x01(\r\"\'\n\nKVResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0b\n\x03ret\x18\x02 \x01(\x05\":\n\x06KVData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0f\n\x07version\x18\x02 \x01(\x04\x12\x11\n\tisdeleted\x18\x03 \x01(\x08\x32\xb8\x01\n\x08KVServer\x12&\n\x03Put\x12\r.kv.KVRequest\x1a\x0e.kv.KVResponse\"\x00\x12+\n\x08GetLocal\x12\r.kv.KVRequest\x1a\x0e.kv.KVResponse\"\x00\x12,\n\tGetGlobal\x12\r.kv.KVRequest\x1a\x0e.kv.KVResponse\"\x00\x12)\n\x06\x44\x65lete\x12\r.kv.KVRequest\x1a\x0e.kv.KVResponse\"\x00\x62\x06proto3')



_KVREQUEST = DESCRIPTOR.message_types_by_name['KVRequest']
_KVRESPONSE = DESCRIPTOR.message_types_by_name['KVResponse']
_KVDATA = DESCRIPTOR.message_types_by_name['KVData']
KVRequest = _reflection.GeneratedProtocolMessageType('KVRequest', (_message.Message,), {
  'DESCRIPTOR' : _KVREQUEST,
  '__module__' : 'kv_pb2'
  # @@protoc_insertion_point(class_scope:kv.KVRequest)
  })
_sym_db.RegisterMessage(KVRequest)

KVResponse = _reflection.GeneratedProtocolMessageType('KVResponse', (_message.Message,), {
  'DESCRIPTOR' : _KVRESPONSE,
  '__module__' : 'kv_pb2'
  # @@protoc_insertion_point(class_scope:kv.KVResponse)
  })
_sym_db.RegisterMessage(KVResponse)

KVData = _reflection.GeneratedProtocolMessageType('KVData', (_message.Message,), {
  'DESCRIPTOR' : _KVDATA,
  '__module__' : 'kv_pb2'
  # @@protoc_insertion_point(class_scope:kv.KVData)
  })
_sym_db.RegisterMessage(KVData)

_KVSERVER = DESCRIPTOR.services_by_name['KVServer']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _KVREQUEST._serialized_start=16
  _KVREQUEST._serialized_end=90
  _KVRESPONSE._serialized_start=92
  _KVRESPONSE._serialized_end=131
  _KVDATA._serialized_start=133
  _KVDATA._serialized_end=191
  _KVSERVER._serialized_start=194
  _KVSERVER._serialized_end=378
# @@protoc_insertion_point(module_scope)
